version: "3"
services:
  db:
    image: linuxserver/mariadb:10.6.13
    volumes:
      - ./mariadb/mariadb-data:/config
    restart: always
    ports:
      - 3306:3306
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: America/Lima

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - ACME_INTERNAL_PASSWORD=121383Loco!
      - DB_USER=acme
      - DB_NAME=acme_db
      - DB_HOST=db
      - DB_PORT=3306
    restart: always
    ports:
      - 9000:9000

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
